# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlnode',
            name='sensor_values',
        ),
        migrations.RemoveField(
            model_name='sensornode',
            name='sensor_values',
        ),
        migrations.AddField(
            model_name='controlnode',
            name='humidity',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='controlnode',
            name='temperature',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='controlnode',
            name='valid',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='sensornode',
            name='humidity',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='sensornode',
            name='temperature',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='sensornode',
            name='valid',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='controlnode',
            name='last_query',
            field=models.DateTimeField(editable=False, verbose_name='Last date queried'),
        ),
        migrations.AlterField(
            model_name='controlnode',
            name='relay_active',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='sensornode',
            name='last_query',
            field=models.DateTimeField(editable=False, verbose_name='Last date queried'),
        ),
        migrations.AlterField(
            model_name='sensornode',
            name='lowBattery',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='targetsettings',
            name='from_time',
            field=models.TimeField(verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='targetsettings',
            name='until_time',
            field=models.TimeField(verbose_name='Until'),
        ),
        migrations.DeleteModel(
            name='DHT11SensorValues',
        ),
    ]
