# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20170725_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetsetting',
            name='temp_unit',
            field=models.CharField(choices=[('Fahrenheit', 'ºF'), ('Celsius', 'ºC')], default='Celsius', max_length=2),
        ),
        migrations.AlterField(
            model_name='controlnode',
            name='last_query',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Last date queried'),
        ),
        migrations.AlterField(
            model_name='sensornode',
            name='last_query',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Last date queried'),
        ),
        migrations.AlterField(
            model_name='targetsetting',
            name='temperature',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Temperature'),
        ),
    ]
