# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17)),
                ('location', models.CharField(max_length=255)),
                ('last_query', models.DateTimeField(verbose_name='Last date queried')),
                ('relay_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DHT11SensorValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.PositiveSmallIntegerField(default=0)),
                ('humidity', models.PositiveSmallIntegerField(default=0)),
                ('valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SensorNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17)),
                ('location', models.CharField(max_length=255)),
                ('last_query', models.DateTimeField(verbose_name='Last date queried')),
                ('lowBattery', models.BooleanField(default=False)),
                ('sensor_values', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.DHT11SensorValues')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TargetSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.PositiveSmallIntegerField(default=0)),
                ('from_time', models.TimeField()),
                ('until_time', models.TimeField()),
                ('priority', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='sensornode',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.TargetSettings'),
        ),
        migrations.AddField(
            model_name='controlnode',
            name='sensor_values',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.DHT11SensorValues'),
        ),
        migrations.AddField(
            model_name='controlnode',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.TargetSettings'),
        ),
    ]
