# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20170725_1116'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TargetSettings',
            new_name='TargetSetting',
        ),
    ]
