# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20170726_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetsetting',
            name='temp_unit',
            field=models.CharField(choices=[('ºF', 'Fahrenheit'), ('ºC', 'Celsius')], default='ºC', max_length=2, verbose_name='Temperature unit'),
        ),
    ]
